#!/bin/bash

commit_message="initial commit"
files_to_commit=()  # Array to hold files to commit

while getopts "b:c:i:m:h" flag; do
    case "${flag}" in
        b) branch_name="${OPTARG}" ;; # this stores the branch name to change
        c) commit_message="${OPTARG}" ;; # this stores the commit message 
        i) files_to_commit+=("${OPTARG}") ;;
        m) files_to_commit+=("${OPTARG}");;
        h) # Display help message
            echo "Usage: commit [-b branch_name] [-c commit_message] [-i file1] [-m file2] [-h]"
            echo ""
            echo "Options:"
            echo "  -b branch_name   : Switch to the specified branch"
            echo "  -c commit_message: Specify the commit message"
            echo "  -i file1         : Add a specific file to commit"
            echo "  -m file2         : Add multiple files to commit"
            echo "  -h               : Display this help message"
            exit 0
            ;;
        *) ;;
    esac
done

clear
figlet "Git!"

# Check if .git directory exists
if [ -e '.git' ]; then
    # Git directory exists

    # Display unstaged files
    echo -e '\e[32m[INFO] Here are all the unstaged files...\e[0m'
    git status
    echo ''
    echo ''

    # Pull any changes from the remote repository
    echo -e -n '\e[32m[INFO] Checking if any files need to be pulled...\e[0m\n'
    git pull

    # Add specified files or all files for staging
    if [ "${#files_to_commit[@]}" -gt 0 ]; then
        for file in "${files_to_commit[@]}"; do
            echo -e "\e[32m[INFO] Adding file: '$file'\e[0m"
            git add "$file"
        done
    else
        echo -e '\e[32m[INFO] Adding all the files...\e[0m'
        git add .
    fi

    # Commit the staged files with the provided message or default message
    echo -e "\e[32m[INFO] Committing files with message: '$commit_message'\e[0m"
    git commit -m "$commit_message"

    # Switch to the specified branch if provided
    if [ -n "$branch_name" ]; then
        echo -e "\e[32m[INFO] Switching to branch: '$branch_name'\e[0m"
        git checkout "$branch_name"
    fi

    # Push the committed changes to the specified or current branch
    echo -e '\e[32m[INFO] Pushing files...\e[0m'
    git push --force

    # Add a 1-second delay for visual effect
    sleep 1

    # Display "Repo Updated" message
    figlet "Repo Updated!!"
else
    # Git directory does not exist
    echo -e '\e[31mFatal Error: Git not initialized!'
    echo -e '\e[31m.git file not found!\e[0m'
fi

